### ISSUE TITLE
Failed to run in travis-ci.org

### ISSUE THREAD

**Issue by wsdjeg** [Vimjas/covimerage#93]
Hi, I just used this project in SpaceVim. and the config file is:

- https://github.com/SpaceVim/SpaceVim/blob/master/Makefile
- https://github.com/SpaceVim/SpaceVim/blob/master/.travis.yml

vader test is successed.

```
Success/Total: 44/44 (assertions: 149/149)
Elapsed time: 4.35 sec.
```
But the job is failed, 

```
bundle/neobundle.vim/autoload/neobundle/commands.vim                                                     489    489     0%
bundle/neobundmake: *** [test_coverage] Error 1
The command ".ci/script.sh" exited with 2.
cache.2
store build cache
````

there is not any useful infomation, I can not debug it.

 here is the job link:

https://travis-ci.org/github/SpaceVim/SpaceVim/jobs/726545335

**Comment by blueyed** [comment]
Closing due to missing info (build log is not available anymore, relevant parts should have been copied here).
Likely related to #94 anyway I guess.
